### ISSUE TITLE
Two links here cannot be accessible!!!, which terribly hindered my research work!!!

### ISSUE THREAD

**Issue by kennyorn1** [XiaoxiaoGuo/fashion-iq#20]
Two links here cannot be accessible!!!
Please, please, plea........se!! repair the problem as soon as possible. Because of this problem, my research work was dramatically, terribly hindered(keep crying wuwuwu...)
So please, don't let us down

I'll appreciate it if this problem is handled. Thanks and thanks a lot!!!
![1673349257257](https://user-images.githubusercontent.com/110704880/211538294-23085318-29d0-4cb4-903b-cba3a7c60659.jpg)

**Comment by cannacak** [comment]
Have you found anything ?

**Comment by kennyorn1** [comment]
Please see this link #18
