### ISSUE TITLE
> The previous link for attributes was broken for some reason. So updated the link for attributes.

### ISSUE THREAD

**Issue by kennyorn1** [XiaoxiaoGuo/fashion-iq#21]
> The previous link for attributes was broken for some reason. So updated the link for attributes.

It broke again, please help, thanks!

1.The URLs in "first link" have many broken links, could you please upload the dataset'images in a more stable way? Thanks a lot!
I download through the URLs, there are hundreds of picture show 0byte, which means I failed to download the picture through URLs.

2.The files in second link are disappeared.

3.The third link cannot been accessible.

The first question is very urgent for me, and also images in a dataset is undoubtedly  very significantIt, so please upload the dataset'images in a more stable way. Thanks and thanks a lot!!

I'll appreciate you if you do that. 
May the Force be with you. Thanks again!

![1673367077307](https://user-images.githubusercontent.com/110704880/211603183-ead9552a-5f39-469c-9d60-643e2b174037.jpg)

_Originally posted by @kennyorn1 in https://github.com/XiaoxiaoGuo/fashion-iq/issues/17#issuecomment-1377513734_

**Comment by sanLiR** [comment]
Hi, have you solved your problem? How can I obtain the completed dataset?

**Comment by kennyorn1** [comment]
> Hi, have you solved your problem? How can I obtain the completed dataset?

Please use this link below.

https://github.com/XiaoxiaoGuo/fashion-iq/issues/18#issue-1181774083
