### ISSUE TITLE
How to solve the problem of broken link in fashioniq

### ISSUE THREAD

**Issue by dafeng-li** [XiaoxiaoGuo/fashion-iq#8]
Hello,
some url links are broken in fashioniq. How can I get the right pictures?

**Comment by zxh19976666** [comment]
> Hello,
> some url links are broken in fashioniq. How can I get the right pictures?

我也在找 根本下载不全

**Comment by dafeng-li** [comment]
> > Hello,
> > some url links are broken in fashioniq. How can I get the right pictures?
> 
> 我也在找 根本下载不全

哎，作者应该把数据集放到云盘上，失效的链接都下载不了

**Comment by dddgggmmm-bit** [comment]
check out [this](https://drive.google.com/file/d/1gv3aAVlqNukupYq0BRXzO-3PBJAg4wZu/view?usp=sharing)

**Comment by dafeng-li** [comment]
> check out [this](https://drive.google.com/file/d/1gv3aAVlqNukupYq0BRXzO-3PBJAg4wZu/view?usp=sharing)

Thanks!

**Comment by zhaohengz** [comment]
Hey guys,

Are you able to retrieve all the data needed?

**Comment by VisualJoyce** [comment]
昨天尝试的结果，大量链接已经失效。
I tried yesterday, thousands of links are dead. 
```shell
(base) vimos@vimosmu ➜  fashion_iq git:(master) ✗ ls -1 image_data/dress | wc -l
18182
(base) vimos@vimosmu ➜  fashion_iq git:(master) ✗ ls -1 image_data/shirt | wc -l
30882
(base) vimos@vimosmu ➜  fashion_iq git:(master) ✗ ls -1 image_data/toptee | wc -l
26329
```

@dafeng-li, are you able to access the google drive link?

**Comment by VisualJoyce** [comment]
如果训练数据缺失，无法修复的话，能否固定一个测试集，使得其图像永久有效？

**Comment by dafeng-li** [comment]
> 昨天尝试的结果，大量链接已经失效。
> I tried yesterday, thousands of links are dead.
> 
> ```shell
> (base) vimos@vimosmu ➜  fashion_iq git:(master) ✗ ls -1 image_data/dress | wc -l
> 18182
> (base) vimos@vimosmu ➜  fashion_iq git:(master) ✗ ls -1 image_data/shirt | wc -l
> 30882
> (base) vimos@vimosmu ➜  fashion_iq git:(master) ✗ ls -1 image_data/toptee | wc -l
> 26329
> ```
> 
> @dafeng-li, are you able to access the google drive link?

**Comment by dafeng-li** [comment]
> 昨天尝试的结果，大量链接已经失效。
> I tried yesterday, thousands of links are dead.
> 
> ```shell
> (base) vimos@vimosmu ➜  fashion_iq git:(master) ✗ ls -1 image_data/dress | wc -l
> 18182
> (base) vimos@vimosmu ➜  fashion_iq git:(master) ✗ ls -1 image_data/shirt | wc -l
> 30882
> (base) vimos@vimosmu ➜  fashion_iq git:(master) ✗ ls -1 image_data/toptee | wc -l
> 26329
> ```
> 
> @dafeng-li, are you able to access the google drive link?

我在上面那个谷歌云盘的链接下载，可以下载成功。

**Comment by VisualJoyce** [comment]
需要申请访问权限，我还没通过。

**Comment by dafeng-li** [comment]
> 需要申请访问权限，我还没通过。

你可以发邮件联系一下作者

**Comment by VisualJoyce** [comment]
> > 需要申请访问权限，我还没通过。
> 
> 你可以发邮件联系一下作者

已经联系过，并且把最新的缺失列表分享了，目前还在等修复措施。

**Comment by VisualJoyce** [comment]
上面的链接也失效了

**Comment by weihao20** [comment]
> 上面的链接也失效了

你好，请问现在有解决的方法了吗

**Comment by xiaoweidao** [comment]
> > 需要申请访问权限，我还没通过。
> 
> 你可以发邮件联系一下作者
你好，你可以再发一下云盘连接吗？

**Comment by sanLiR** [comment]
> > 上面的链接也失效了
> 
> 你好，请问现在有解决的方法了吗

你好，你现在解决了吗？

**Comment by zxh19976666** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
